INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (1,21,'Kabupaten','Aceh Barat','23681', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (2,21,'Kabupaten','Aceh Barat Daya','23764', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (3,21,'Kabupaten','Aceh Besar','23951', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (4,21,'Kabupaten','Aceh Jaya','23654', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (5,21,'Kabupaten','Aceh Selatan','23719', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (6,21,'Kabupaten','Aceh Singkil','24785', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (7,21,'Kabupaten','Aceh Tamiang','24476', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (8,21,'Kabupaten','Aceh Tengah','24511', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (9,21,'Kabupaten','Aceh Tenggara','24611', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (10,21,'Kabupaten','Aceh Timur','24454', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (11,21,'Kabupaten','Aceh Utara','24382', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (12,32,'Kabupaten','Agam','26411', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (13,23,'Kabupaten','Alor','85811', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (14,19,'Kota','Ambon','97222', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (15,34,'Kabupaten','Asahan','21214', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (16,24,'Kabupaten','Asmat','99777', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (17,1,'Kabupaten','Badung','80351', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (18,13,'Kabupaten','Balangan','71611', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (19,15,'Kota','Balikpapan','76111', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (20,21,'Kota','Banda Aceh','23238', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (21,18,'Kota','Bandar Lampung','35139', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (22,9,'Kabupaten','Bandung','40311', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (23,9,'Kota','Bandung','40111', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (24,9,'Kabupaten','Bandung Barat','40721', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (25,29,'Kabupaten','Banggai','94711', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (26,29,'Kabupaten','Banggai Kepulauan','94881', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (27,2,'Kabupaten','Bangka','33212', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (28,2,'Kabupaten','Bangka Barat','33315', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (29,2,'Kabupaten','Bangka Selatan','33719', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (30,2,'Kabupaten','Bangka Tengah','33613', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (31,11,'Kabupaten','Bangkalan','69118', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (32,1,'Kabupaten','Bangli','80619', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (33,13,'Kabupaten','Banjar','70619', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (34,9,'Kota','Banjar','46311', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (35,13,'Kota','Banjarbaru','70712', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (36,13,'Kota','Banjarmasin','70117', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (37,10,'Kabupaten','Banjarnegara','53419', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (38,28,'Kabupaten','Bantaeng','92411', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (39,5,'Kabupaten','Bantul','55715', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (40,33,'Kabupaten','Banyuasin','30911', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (41,10,'Kabupaten','Banyumas','53114', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (42,11,'Kabupaten','Banyuwangi','68416', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (43,13,'Kabupaten','Barito Kuala','70511', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (44,14,'Kabupaten','Barito Selatan','73711', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (45,14,'Kabupaten','Barito Timur','73671', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (46,14,'Kabupaten','Barito Utara','73881', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (47,28,'Kabupaten','Barru','90719', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (48,17,'Kota','Batam','29413', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (49,10,'Kabupaten','Batang','51211', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (50,8,'Kabupaten','Batang Hari','36613', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (51,11,'Kota','Batu','65311', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (52,34,'Kabupaten','Batu Bara','21655', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (53,30,'Kota','Bau-Bau','93719', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (54,9,'Kabupaten','Bekasi','17837', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (55,9,'Kota','Bekasi','17121', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (56,2,'Kabupaten','Belitung','33419', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (57,2,'Kabupaten','Belitung Timur','33519', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (58,23,'Kabupaten','Belu','85711', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (59,21,'Kabupaten','Bener Meriah','24581', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (60,26,'Kabupaten','Bengkalis','28719', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (61,12,'Kabupaten','Bengkayang','79213', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (62,4,'Kota','Bengkulu','38229', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (63,4,'Kabupaten','Bengkulu Selatan','38519', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (64,4,'Kabupaten','Bengkulu Tengah','38319', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (65,4,'Kabupaten','Bengkulu Utara','38619', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (66,15,'Kabupaten','Berau','77311', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (67,24,'Kabupaten','Biak Numfor','98119', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (68,22,'Kabupaten','Bima','84171', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (69,22,'Kota','Bima','84139', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (70,34,'Kota','Binjai','20712', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (71,17,'Kabupaten','Bintan','29135', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (72,21,'Kabupaten','Bireuen','24219', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (73,31,'Kota','Bitung','95512', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (74,11,'Kabupaten','Blitar','66171', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (75,11,'Kota','Blitar','66124', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (76,10,'Kabupaten','Blora','58219', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (77,7,'Kabupaten','Boalemo','96319', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (78,9,'Kabupaten','Bogor','16911', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (79,9,'Kota','Bogor','16119', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (80,11,'Kabupaten','Bojonegoro','62119', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (81,31,'Kabupaten','Bolaang Mongondow (Bolmong)','95755', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (82,31,'Kabupaten','Bolaang Mongondow Selatan','95774', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (83,31,'Kabupaten','Bolaang Mongondow Timur','95783', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (84,31,'Kabupaten','Bolaang Mongondow Utara','95765', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (85,30,'Kabupaten','Bombana','93771', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (86,11,'Kabupaten','Bondowoso','68219', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (87,28,'Kabupaten','Bone','92713', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (88,7,'Kabupaten','Bone Bolango','96511', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (89,15,'Kota','Bontang','75313', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (90,24,'Kabupaten','Boven Digoel','99662', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (91,10,'Kabupaten','Boyolali','57312', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (92,10,'Kabupaten','Brebes','52212', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (93,32,'Kota','Bukittinggi','26115', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (94,1,'Kabupaten','Buleleng','81111', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (95,28,'Kabupaten','Bulukumba','92511', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (96,16,'Kabupaten','Bulungan (Bulongan)','77211', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (97,8,'Kabupaten','Bungo','37216', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (98,29,'Kabupaten','Buol','94564', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (99,19,'Kabupaten','Buru','97371', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (100,19,'Kabupaten','Buru Selatan','97351', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (101,30,'Kabupaten','Buton','93754', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (102,30,'Kabupaten','Buton Utara','93745', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (103,9,'Kabupaten','Ciamis','46211', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (104,9,'Kabupaten','Cianjur','43217', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (105,10,'Kabupaten','Cilacap','53211', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (106,3,'Kota','Cilegon','42417', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (107,9,'Kota','Cimahi','40512', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (108,9,'Kabupaten','Cirebon','45611', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (109,9,'Kota','Cirebon','45116', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (110,34,'Kabupaten','Dairi','22211', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (111,24,'Kabupaten','Deiyai (Deliyai)','98784', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (112,34,'Kabupaten','Deli Serdang','20511', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (113,10,'Kabupaten','Demak','59519', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (114,1,'Kota','Denpasar','80227', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (115,9,'Kota','Depok','16416', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (116,32,'Kabupaten','Dharmasraya','27612', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (117,24,'Kabupaten','Dogiyai','98866', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (118,22,'Kabupaten','Dompu','84217', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (119,29,'Kabupaten','Donggala','94341', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (120,26,'Kota','Dumai','28811', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (121,33,'Kabupaten','Empat Lawang','31811', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (122,23,'Kabupaten','Ende','86351', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (123,28,'Kabupaten','Enrekang','91719', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (124,25,'Kabupaten','Fakfak','98651', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (125,23,'Kabupaten','Flores Timur','86213', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (126,9,'Kabupaten','Garut','44126', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (127,21,'Kabupaten','Gayo Lues','24653', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (128,1,'Kabupaten','Gianyar','80519', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (129,7,'Kabupaten','Gorontalo','96218', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (130,7,'Kota','Gorontalo','96115', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (131,7,'Kabupaten','Gorontalo Utara','96611', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (132,28,'Kabupaten','Gowa','92111', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (133,11,'Kabupaten','Gresik','61115', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (134,10,'Kabupaten','Grobogan','58111', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (135,5,'Kabupaten','Gunung Kidul','55812', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (136,14,'Kabupaten','Gunung Mas','74511', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (137,34,'Kota','Gunungsitoli','22813', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (138,20,'Kabupaten','Halmahera Barat','97757', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (139,20,'Kabupaten','Halmahera Selatan','97911', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (140,20,'Kabupaten','Halmahera Tengah','97853', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (141,20,'Kabupaten','Halmahera Timur','97862', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (142,20,'Kabupaten','Halmahera Utara','97762', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (143,13,'Kabupaten','Hulu Sungai Selatan','71212', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (144,13,'Kabupaten','Hulu Sungai Tengah','71313', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (145,13,'Kabupaten','Hulu Sungai Utara','71419', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (146,34,'Kabupaten','Humbang Hasundutan','22457', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (147,26,'Kabupaten','Indragiri Hilir','29212', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (148,26,'Kabupaten','Indragiri Hulu','29319', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (149,9,'Kabupaten','Indramayu','45214', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (150,24,'Kabupaten','Intan Jaya','98771', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (151,6,'Kota','Jakarta Barat','11220', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (152,6,'Kota','Jakarta Pusat','10540', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (153,6,'Kota','Jakarta Selatan','12230', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (154,6,'Kota','Jakarta Timur','13330', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (155,6,'Kota','Jakarta Utara','14140', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (156,8,'Kota','Jambi','36111', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (157,24,'Kabupaten','Jayapura','99352', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (158,24,'Kota','Jayapura','99114', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (159,24,'Kabupaten','Jayawijaya','99511', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (160,11,'Kabupaten','Jember','68113', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (161,1,'Kabupaten','Jembrana','82251', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (162,28,'Kabupaten','Jeneponto','92319', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (163,10,'Kabupaten','Jepara','59419', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (164,11,'Kabupaten','Jombang','61415', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (165,25,'Kabupaten','Kaimana','98671', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (166,26,'Kabupaten','Kampar','28411', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (167,14,'Kabupaten','Kapuas','73583', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (168,12,'Kabupaten','Kapuas Hulu','78719', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (169,10,'Kabupaten','Karanganyar','57718', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (170,1,'Kabupaten','Karangasem','80819', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (171,9,'Kabupaten','Karawang','41311', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (172,17,'Kabupaten','Karimun','29611', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (173,34,'Kabupaten','Karo','22119', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (174,14,'Kabupaten','Katingan','74411', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (175,4,'Kabupaten','Kaur','38911', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (176,12,'Kabupaten','Kayong Utara','78852', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (177,10,'Kabupaten','Kebumen','54319', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (178,11,'Kabupaten','Kediri','64184', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (179,11,'Kota','Kediri','64125', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (180,24,'Kabupaten','Keerom','99461', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (181,10,'Kabupaten','Kendal','51314', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (182,30,'Kota','Kendari','93126', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (183,4,'Kabupaten','Kepahiang','39319', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (184,17,'Kabupaten','Kepulauan Anambas','29991', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (185,19,'Kabupaten','Kepulauan Aru','97681', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (186,32,'Kabupaten','Kepulauan Mentawai','25771', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (187,26,'Kabupaten','Kepulauan Meranti','28791', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (188,31,'Kabupaten','Kepulauan Sangihe','95819', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (189,6,'Kabupaten','Kepulauan Seribu','14550', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (190,31,'Kabupaten','Kepulauan Siau Tagulandang Biaro (Sitaro)','95862', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (191,20,'Kabupaten','Kepulauan Sula','97995', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (192,31,'Kabupaten','Kepulauan Talaud','95885', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (193,24,'Kabupaten','Kepulauan Yapen (Yapen Waropen)','98211', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (194,8,'Kabupaten','Kerinci','37167', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (195,12,'Kabupaten','Ketapang','78874', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (196,10,'Kabupaten','Klaten','57411', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (197,1,'Kabupaten','Klungkung','80719', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (198,30,'Kabupaten','Kolaka','93511', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (199,30,'Kabupaten','Kolaka Utara','93911', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (200,30,'Kabupaten','Konawe','93411', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (201,30,'Kabupaten','Konawe Selatan','93811', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (202,30,'Kabupaten','Konawe Utara','93311', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (203,13,'Kabupaten','Kotabaru','72119', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (204,31,'Kota','Kotamobagu','95711', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (205,14,'Kabupaten','Kotawaringin Barat','74119', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (206,14,'Kabupaten','Kotawaringin Timur','74364', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (207,26,'Kabupaten','Kuantan Singingi','29519', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (208,12,'Kabupaten','Kubu Raya','78311', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (209,10,'Kabupaten','Kudus','59311', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (210,5,'Kabupaten','Kulon Progo','55611', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (211,9,'Kabupaten','Kuningan','45511', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (212,23,'Kabupaten','Kupang','85362', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (213,23,'Kota','Kupang','85119', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (214,15,'Kabupaten','Kutai Barat','75711', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (215,15,'Kabupaten','Kutai Kartanegara','75511', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (216,15,'Kabupaten','Kutai Timur','75611', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (217,34,'Kabupaten','Labuhan Batu','21412', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (218,34,'Kabupaten','Labuhan Batu Selatan','21511', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (219,34,'Kabupaten','Labuhan Batu Utara','21711', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (220,33,'Kabupaten','Lahat','31419', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (221,14,'Kabupaten','Lamandau','74611', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (222,11,'Kabupaten','Lamongan','64125', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (223,18,'Kabupaten','Lampung Barat','34814', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (224,18,'Kabupaten','Lampung Selatan','35511', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (225,18,'Kabupaten','Lampung Tengah','34212', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (226,18,'Kabupaten','Lampung Timur','34319', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (227,18,'Kabupaten','Lampung Utara','34516', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (228,12,'Kabupaten','Landak','78319', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (229,34,'Kabupaten','Langkat','20811', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (230,21,'Kota','Langsa','24412', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (231,24,'Kabupaten','Lanny Jaya','99531', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (232,3,'Kabupaten','Lebak','42319', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (233,4,'Kabupaten','Lebong','39264', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (234,23,'Kabupaten','Lembata','86611', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (235,21,'Kota','Lhokseumawe','24352', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (236,32,'Kabupaten','Lima Puluh Koto/Kota','26671', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (237,17,'Kabupaten','Lingga','29811', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (238,22,'Kabupaten','Lombok Barat','83311', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (239,22,'Kabupaten','Lombok Tengah','83511', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (240,22,'Kabupaten','Lombok Timur','83612', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (241,22,'Kabupaten','Lombok Utara','83711', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (242,33,'Kota','Lubuk Linggau','31614', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (243,11,'Kabupaten','Lumajang','67319', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (244,28,'Kabupaten','Luwu','91994', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (245,28,'Kabupaten','Luwu Timur','92981', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (246,28,'Kabupaten','Luwu Utara','92911', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (247,11,'Kabupaten','Madiun','63153', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (248,11,'Kota','Madiun','63122', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (249,10,'Kabupaten','Magelang','56519', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (250,10,'Kota','Magelang','56133', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (251,11,'Kabupaten','Magetan','63314', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (252,9,'Kabupaten','Majalengka','45412', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (253,27,'Kabupaten','Majene','91411', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (254,28,'Kota','Makassar','90111', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (255,11,'Kabupaten','Malang','65163', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (256,11,'Kota','Malang','65112', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (257,16,'Kabupaten','Malinau','77511', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (258,19,'Kabupaten','Maluku Barat Daya','97451', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (259,19,'Kabupaten','Maluku Tengah','97513', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (260,19,'Kabupaten','Maluku Tenggara','97651', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (261,19,'Kabupaten','Maluku Tenggara Barat','97465', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (262,27,'Kabupaten','Mamasa','91362', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (263,24,'Kabupaten','Mamberamo Raya','99381', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (264,24,'Kabupaten','Mamberamo Tengah','99553', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (265,27,'Kabupaten','Mamuju','91519', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (266,27,'Kabupaten','Mamuju Utara','91571', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (267,31,'Kota','Manado','95247', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (268,34,'Kabupaten','Mandailing Natal','22916', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (269,23,'Kabupaten','Manggarai','86551', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (270,23,'Kabupaten','Manggarai Barat','86711', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (271,23,'Kabupaten','Manggarai Timur','86811', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (272,25,'Kabupaten','Manokwari','98311', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (273,25,'Kabupaten','Manokwari Selatan','98355', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (274,24,'Kabupaten','Mappi','99853', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (275,28,'Kabupaten','Maros','90511', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (276,22,'Kota','Mataram','83131', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (277,25,'Kabupaten','Maybrat','98051', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (278,34,'Kota','Medan','20228', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (279,12,'Kabupaten','Melawi','78619', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (280,8,'Kabupaten','Merangin','37319', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (281,24,'Kabupaten','Merauke','99613', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (282,18,'Kabupaten','Mesuji','34911', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (283,18,'Kota','Metro','34111', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (284,24,'Kabupaten','Mimika','99962', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (285,31,'Kabupaten','Minahasa','95614', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (286,31,'Kabupaten','Minahasa Selatan','95914', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (287,31,'Kabupaten','Minahasa Tenggara','95995', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (288,31,'Kabupaten','Minahasa Utara','95316', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (289,11,'Kabupaten','Mojokerto','61382', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (290,11,'Kota','Mojokerto','61316', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (291,29,'Kabupaten','Morowali','94911', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (292,33,'Kabupaten','Muara Enim','31315', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (293,8,'Kabupaten','Muaro Jambi','36311', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (294,4,'Kabupaten','Muko Muko','38715', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (295,30,'Kabupaten','Muna','93611', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (296,14,'Kabupaten','Murung Raya','73911', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (297,33,'Kabupaten','Musi Banyuasin','30719', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (298,33,'Kabupaten','Musi Rawas','31661', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (299,24,'Kabupaten','Nabire','98816', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (300,21,'Kabupaten','Nagan Raya','23674', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (301,23,'Kabupaten','Nagekeo','86911', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (302,17,'Kabupaten','Natuna','29711', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (303,24,'Kabupaten','Nduga','99541', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (304,23,'Kabupaten','Ngada','86413', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (305,11,'Kabupaten','Nganjuk','64414', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (306,11,'Kabupaten','Ngawi','63219', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (307,34,'Kabupaten','Nias','22876', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (308,34,'Kabupaten','Nias Barat','22895', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (309,34,'Kabupaten','Nias Selatan','22865', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (310,34,'Kabupaten','Nias Utara','22856', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (311,16,'Kabupaten','Nunukan','77421', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (312,33,'Kabupaten','Ogan Ilir','30811', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (313,33,'Kabupaten','Ogan Komering Ilir','30618', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (314,33,'Kabupaten','Ogan Komering Ulu','32112', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (315,33,'Kabupaten','Ogan Komering Ulu Selatan','32211', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (316,33,'Kabupaten','Ogan Komering Ulu Timur','32312', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (317,11,'Kabupaten','Pacitan','63512', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (318,32,'Kota','Padang','25112', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (319,34,'Kabupaten','Padang Lawas','22763', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (320,34,'Kabupaten','Padang Lawas Utara','22753', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (321,32,'Kota','Padang Panjang','27122', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (322,32,'Kabupaten','Padang Pariaman','25583', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (323,34,'Kota','Padang Sidempuan','22727', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (324,33,'Kota','Pagar Alam','31512', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (325,34,'Kabupaten','Pakpak Bharat','22272', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (326,14,'Kota','Palangka Raya','73112', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (327,33,'Kota','Palembang','30111', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (328,28,'Kota','Palopo','91911', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (329,29,'Kota','Palu','94111', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (330,11,'Kabupaten','Pamekasan','69319', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (331,3,'Kabupaten','Pandeglang','42212', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (332,9,'Kabupaten','Pangandaran','46511', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (333,28,'Kabupaten','Pangkajene Kepulauan','90611', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (334,2,'Kota','Pangkal Pinang','33115', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (335,24,'Kabupaten','Paniai','98765', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (336,28,'Kota','Parepare','91123', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (337,32,'Kota','Pariaman','25511', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (338,29,'Kabupaten','Parigi Moutong','94411', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (339,32,'Kabupaten','Pasaman','26318', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (340,32,'Kabupaten','Pasaman Barat','26511', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (341,15,'Kabupaten','Paser','76211', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (342,11,'Kabupaten','Pasuruan','67153', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (343,11,'Kota','Pasuruan','67118', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (344,10,'Kabupaten','Pati','59114', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (345,32,'Kota','Payakumbuh','26213', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (346,25,'Kabupaten','Pegunungan Arfak','98354', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (347,24,'Kabupaten','Pegunungan Bintang','99573', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (348,10,'Kabupaten','Pekalongan','51161', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (349,10,'Kota','Pekalongan','51122', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (350,26,'Kota','Pekanbaru','28112', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (351,26,'Kabupaten','Pelalawan','28311', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (352,10,'Kabupaten','Pemalang','52319', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (353,34,'Kota','Pematang Siantar','21126', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (354,15,'Kabupaten','Penajam Paser Utara','76311', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (355,18,'Kabupaten','Pesawaran','35312', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (356,18,'Kabupaten','Pesisir Barat','35974', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (357,32,'Kabupaten','Pesisir Selatan','25611', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (358,21,'Kabupaten','Pidie','24116', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (359,21,'Kabupaten','Pidie Jaya','24186', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (360,28,'Kabupaten','Pinrang','91251', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (361,7,'Kabupaten','Pohuwato','96419', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (362,27,'Kabupaten','Polewali Mandar','91311', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (363,11,'Kabupaten','Ponorogo','63411', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (364,12,'Kabupaten','Pontianak','78971', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (365,12,'Kota','Pontianak','78112', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (366,29,'Kabupaten','Poso','94615', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (367,33,'Kota','Prabumulih','31121', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (368,18,'Kabupaten','Pringsewu','35719', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (369,11,'Kabupaten','Probolinggo','67282', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (370,11,'Kota','Probolinggo','67215', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (371,14,'Kabupaten','Pulang Pisau','74811', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (372,20,'Kabupaten','Pulau Morotai','97771', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (373,24,'Kabupaten','Puncak','98981', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (374,24,'Kabupaten','Puncak Jaya','98979', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (375,10,'Kabupaten','Purbalingga','53312', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (376,9,'Kabupaten','Purwakarta','41119', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (377,10,'Kabupaten','Purworejo','54111', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (378,25,'Kabupaten','Raja Ampat','98489', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (379,4,'Kabupaten','Rejang Lebong','39112', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (380,10,'Kabupaten','Rembang','59219', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (381,26,'Kabupaten','Rokan Hilir','28992', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (382,26,'Kabupaten','Rokan Hulu','28511', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (383,23,'Kabupaten','Rote Ndao','85982', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (384,21,'Kota','Sabang','23512', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (385,23,'Kabupaten','Sabu Raijua','85391', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (386,10,'Kota','Salatiga','50711', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (387,15,'Kota','Samarinda','75133', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (388,12,'Kabupaten','Sambas','79453', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (389,34,'Kabupaten','Samosir','22392', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (390,11,'Kabupaten','Sampang','69219', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (391,12,'Kabupaten','Sanggau','78557', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (392,24,'Kabupaten','Sarmi','99373', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (393,8,'Kabupaten','Sarolangun','37419', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (394,32,'Kota','Sawah Lunto','27416', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (395,12,'Kabupaten','Sekadau','79583', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (396,28,'Kabupaten','Selayar (Kepulauan Selayar)','92812', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (397,4,'Kabupaten','Seluma','38811', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (398,10,'Kabupaten','Semarang','50511', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (399,10,'Kota','Semarang','50135', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (400,19,'Kabupaten','Seram Bagian Barat','97561', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (401,19,'Kabupaten','Seram Bagian Timur','97581', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (402,3,'Kabupaten','Serang','42182', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (403,3,'Kota','Serang','42111', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (404,34,'Kabupaten','Serdang Bedagai','20915', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (405,14,'Kabupaten','Seruyan','74211', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (406,26,'Kabupaten','Siak','28623', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (407,34,'Kota','Sibolga','22522', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (408,28,'Kabupaten','Sidenreng Rappang/Rapang','91613', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (409,11,'Kabupaten','Sidoarjo','61219', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (410,29,'Kabupaten','Sigi','94364', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (411,32,'Kabupaten','Sijunjung (Sawah Lunto Sijunjung)','27511', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (412,23,'Kabupaten','Sikka','86121', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (413,34,'Kabupaten','Simalungun','21162', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (414,21,'Kabupaten','Simeulue','23891', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (415,12,'Kota','Singkawang','79117', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (416,28,'Kabupaten','Sinjai','92615', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (417,12,'Kabupaten','Sintang','78619', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (418,11,'Kabupaten','Situbondo','68316', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (419,5,'Kabupaten','Sleman','55513', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (420,32,'Kabupaten','Solok','27365', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (421,32,'Kota','Solok','27315', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (422,32,'Kabupaten','Solok Selatan','27779', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (423,28,'Kabupaten','Soppeng','90812', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (424,25,'Kabupaten','Sorong','98431', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (425,25,'Kota','Sorong','98411', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (426,25,'Kabupaten','Sorong Selatan','98454', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (427,10,'Kabupaten','Sragen','57211', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (428,9,'Kabupaten','Subang','41215', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (429,21,'Kota','Subulussalam','24882', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (430,9,'Kabupaten','Sukabumi','43311', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (431,9,'Kota','Sukabumi','43114', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (432,14,'Kabupaten','Sukamara','74712', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (433,10,'Kabupaten','Sukoharjo','57514', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (434,23,'Kabupaten','Sumba Barat','87219', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (435,23,'Kabupaten','Sumba Barat Daya','87453', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (436,23,'Kabupaten','Sumba Tengah','87358', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (437,23,'Kabupaten','Sumba Timur','87112', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (438,22,'Kabupaten','Sumbawa','84315', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (439,22,'Kabupaten','Sumbawa Barat','84419', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (440,9,'Kabupaten','Sumedang','45326', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (441,11,'Kabupaten','Sumenep','69413', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (442,8,'Kota','Sungaipenuh','37113', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (443,24,'Kabupaten','Supiori','98164', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (444,11,'Kota','Surabaya','60119', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (445,10,'Kota','Surakarta (Solo)','57113', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (446,13,'Kabupaten','Tabalong','71513', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (447,1,'Kabupaten','Tabanan','82119', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (448,28,'Kabupaten','Takalar','92212', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (449,25,'Kabupaten','Tambrauw','98475', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (450,16,'Kabupaten','Tana Tidung','77611', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (451,28,'Kabupaten','Tana Toraja','91819', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (452,13,'Kabupaten','Tanah Bumbu','72211', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (453,32,'Kabupaten','Tanah Datar','27211', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (454,13,'Kabupaten','Tanah Laut','70811', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (455,3,'Kabupaten','Tangerang','15914', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (456,3,'Kota','Tangerang','15111', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (457,3,'Kota','Tangerang Selatan','15435', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (458,18,'Kabupaten','Tanggamus','35619', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (459,34,'Kota','Tanjung Balai','21321', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (460,8,'Kabupaten','Tanjung Jabung Barat','36513', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (461,8,'Kabupaten','Tanjung Jabung Timur','36719', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (462,17,'Kota','Tanjung Pinang','29111', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (463,34,'Kabupaten','Tapanuli Selatan','22742', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (464,34,'Kabupaten','Tapanuli Tengah','22611', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (465,34,'Kabupaten','Tapanuli Utara','22414', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (466,13,'Kabupaten','Tapin','71119', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (467,16,'Kota','Tarakan','77114', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (468,9,'Kabupaten','Tasikmalaya','46411', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (469,9,'Kota','Tasikmalaya','46116', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (470,34,'Kota','Tebing Tinggi','20632', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (471,8,'Kabupaten','Tebo','37519', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (472,10,'Kabupaten','Tegal','52419', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (473,10,'Kota','Tegal','52114', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (474,25,'Kabupaten','Teluk Bintuni','98551', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (475,25,'Kabupaten','Teluk Wondama','98591', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (476,10,'Kabupaten','Temanggung','56212', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (477,20,'Kota','Ternate','97714', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (478,20,'Kota','Tidore Kepulauan','97815', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (479,23,'Kabupaten','Timor Tengah Selatan','85562', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (480,23,'Kabupaten','Timor Tengah Utara','85612', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (481,34,'Kabupaten','Toba Samosir','22316', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (482,29,'Kabupaten','Tojo Una-Una','94683', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (483,29,'Kabupaten','Toli-Toli','94542', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (484,24,'Kabupaten','Tolikara','99411', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (485,31,'Kota','Tomohon','95416', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (486,28,'Kabupaten','Toraja Utara','91831', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (487,11,'Kabupaten','Trenggalek','66312', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (488,19,'Kota','Tual','97612', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (489,11,'Kabupaten','Tuban','62319', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (490,18,'Kabupaten','Tulang Bawang','34613', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (491,18,'Kabupaten','Tulang Bawang Barat','34419', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (492,11,'Kabupaten','Tulungagung','66212', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (493,28,'Kabupaten','Wajo','90911', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (494,30,'Kabupaten','Wakatobi','93791', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (495,24,'Kabupaten','Waropen','98269', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (496,18,'Kabupaten','Way Kanan','34711', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (497,10,'Kabupaten','Wonogiri','57619', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (498,10,'Kabupaten','Wonosobo','56311', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (499,24,'Kabupaten','Yahukimo','99041', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (500,24,'Kabupaten','Yalimo','99481', NOW(), NOW());
INSERT INTO app_kabkota(id_kabkota,id_propinsi,type,nm_kabkota,postal_code, created_at, updated_at) VALUES (501,5,'Kota','Yogyakarta','55111', NOW(), NOW());
