INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (1,'Bali', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (2,'Bangka Belitung', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (3,'Banten', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (4,'Bengkulu', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (5,'DI Yogyakarta', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (6,'DKI Jakarta', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (7,'Gorontalo', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (8,'Jambi', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (9,'Jawa Barat', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (10,'Jawa Tengah', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (11,'Jawa Timur', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (12,'Kalimantan Barat', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (13,'Kalimantan Selatan', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (14,'Kalimantan Tengah', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (15,'Kalimantan Timur', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (16,'Kalimantan Utara', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (17,'Kepulauan Riau', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (18,'Lampung', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (19,'Maluku', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (20,'Maluku Utara', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (21,'Nanggroe Aceh Darussalam (NAD)', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (22,'Nusa Tenggara Barat (NTB)', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (23,'Nusa Tenggara Timur (NTT)', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (24,'Papua', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (25,'Papua Barat', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (26,'Riau', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (27,'Sulawesi Barat', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (28,'Sulawesi Selatan', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (29,'Sulawesi Tengah', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (30,'Sulawesi Tenggara', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (31,'Sulawesi Utara', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (32,'Sumatera Barat', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (33,'Sumatera Selatan', NOW(), NOW());
INSERT INTO app_propinsi(id_propinsi,nm_propinsi, created_at, updated_at) VALUES (34,'Sumatera Utara', NOW(), NOW());
